# Generated by Django 3.2.8 on 2022-12-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_remove_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='amount',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
